brouter-core/src/main/java/btools/router/OsmTrack.java
Always include messages (csv data) in GeoJSON format. Used by new data tab in brouter-web.
brouter-web master would be ready for deployment, but can wait, planning to add some requested features.
=> Add messages to GeoJSON

brouter-server/src/main/java/btools/server/RouteServer.java
Fixes nrenner/brouter-web#12
Before a profile upload, Safari seems to send a CORS (Cross-Origin Resource Sharing) preflight (``OPTIONS``) request to get permission for a ``POST`` request with a ``Content-Type`` header.
This handles the ``OPTIONS`` request and responds with the appropriate headers.
No dependencies on brouter-web.
=> handle CORS preflight request for profile upload (Safari)

brouter-routing-app/pom.xml, brouter-server/pom.xml, brouter-util/pom.xml, pom.xml
=> update all Maven poms to 1.3.2

misc/scripts/standalone/server.sh
Use segments4 for standalone server, uses version four of the map data files.
=> segments4 for standalone server

misc/scripts/standalone/server.cmd
As a follow-up to #52, also updates the server.cmd script.
=> update standalone server.cmd to segments4

.gitignore
makes
git status
easier to use
=> ignore Intellij project files

misc/readmes/readme.txt
appended a reference to project's github issues page
=> typos in readme fixed

brouter-core/src/main/java/btools/router/OsmPath.java, brouter-core/src/main/java/btools/router/StdPath.java
Hi Arndt,
Thanks for the merge! I saw you pushed an extra commit (https://github.com/abrensch/brouter/commit/6e6c4a18b21db90e9106bafe0be03fcb9b51d4fc), which is totally fine for me. There is just one slight issue, which is fixed in this PR, in that the `computeKinematic` method was not called :/
Best,
=> Fix travel time computation

brouter-server/src/main/java/btools/server/request/ServerHandler.java
This would let users specify the expected name in the resulting file. Fix for #90.
=> Add a "trackName" GET parameter to the server part

brouter-core/src/main/java/btools/router/RoutingContext.java, brouter-core/src/main/java/btools/router/StdPath.java
Hi,
Here are a few improvements for travel time computation:
* Takes `costfactor` into account for switching to walking mode.
* Better energy computation in hiking mode.
* Reword the `bikerMass` to make it clearer for different modes.
Thanks!
=> Few fixes to travel time computation

brouter-server/pom.xml
=> Remove old dependency

misc/profiles2/lookups.dat
As asked in https://github.com/abrensch/brouter/issues/183#issuecomment-526929596.
=> Add support for traffic_signals:direction, see #183.

.gitignore, .idea/runConfigurations/RouteServer.xml
So that new developers can easily start brouter for the first time. Since I only use brouter with brouter-web, I'm only using RouteServer and not the others (CLI, etc.).
=> Add IDEA configuration

.idea/runConfigurations/RouteServer.xml
=> Make paths consistent with server.sh

misc/scripts/standalone/server.sh
It's relative to profiles2 dir
=> Fix server.sh customprofiles path

misc/profiles2/car-vario.brf, misc/profiles2/fastbike-verylowtraffic.brf, misc/profiles2/fastbike.brf, misc/profiles2/moped.brf, misc/profiles2/shortest.brf, misc/profiles2/trekking.brf, misc/profiles2/vm-forum-liegerad-schnell.brf, misc/profiles2/vm-forum-velomobil-schnell.brf
use the brouter-web options for profile adjustment
=> update vm-forum profiles

brouter-core/src/main/java/btools/router/OsmTrack.java, brouter-map-creator/build.gradle, brouter-routing-app/build.gradle, brouter-server/build.gradle, brouter-server/src/main/java/btools/server/BRouter.java, brouter-server/src/main/java/btools/server/RouteServer.java, build.gradle
Tried more normalization on version code.
But didn't find a way to have version code for all situations - Android and Java. 
So we still have 3 points to change when version changes:
```
main build.gradle
app build.gradle (versionCode only)
OsmTrack (version and versionDate)
```
=> Migrate to gradle part 4 #315

brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java, brouter-routing-app/src/main/java/btools/routingapp/DownloadService.java
Change the connection test at start to newer functions. #321 #322
=> Change connection test #321

README.md
I corrected a mistake in the README build instructions (`farJar` -> `fatJar`) and attempted to make the build instructions a little clearer.
Please read the commands and check that I have not made any mistakes, and let me know if I should revert some of the changes!
See also some of the discussion in #320 for context.
=> Corrected and improved README

misc/readmes/readme.txt
Osmand got elevation profile diagrams since some versions:
=> Add Osmand elevation profile diagram

brouter-core/src/main/java/btools/router/OsmNogoPolygon.java
For Nogo-polylines in the first step there is an enclosing circle calculated that contains all segments of the polygon. Only if an endpoint of a segment is within the polygon's enclosing circle each segment of the polygon is checked whether it intersects the current way's segment.
Whenever an endpoint of a way-segment that would intersect a polygon segment is very, very close to the enclosing circle it eventually happens that due to limited numerical precision (caused by the approximation of spherical geometrics) it may be calculated as being outside the polygon's enclosing circle while actually intersecting the nogo-polygon. In such a case the routing algorithem makes use of this segment eventually finding a route that penetrates the polygon.
The fix first of all makes sure the math …
=> fix issue #288 (No-go polyline sometimes leaky)

brouter-server/src/main/java/btools/server/request/ServerHandler.java
Cf https://github.com/nrenner/brouter-web/issues/427
=> Avoid error if missing poi name

brouter-server/build.gradle, misc/profiles2/car-vario.brf, misc/profiles2/trekking.brf
Add use_sidepath from #335.
Add the missed car-vario
=> normalize profiles #312, add use_sidepath #335

.github/workflows/gradle.yml, brouter-codec/build.gradle, brouter-core/build.gradle
=> Revert "Update from abrensch/brouter"

brouter-routing-app/src/main/AndroidManifest.xml, brouter-routing-app/src/main/java/btools/routingapp/BImportActivity.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java, brouter-routing-app/src/main/java/btools/routingapp/DownloadService.java, brouter-routing-app/src/main/java/btools/routingapp/ServerConfig.java, brouter-routing-app/src/main/res/layout/import_intent.xml, brouter-routing-app/src/main/res/values/strings.xml
Fixes #362
Implementation from @EssBee59
=> Add intent receiver for profiles

.git-blame-ignore-revs, brouter-routing-app/src/main/java/btools/routingapp/AppLogger.java, brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java, brouter-routing-app/src/main/java/btools/routingapp/BInstallerView.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java, brouter-routing-app/src/main/java/btools/routingapp/ConfigHelper.java, brouter-routing-app/src/main/java/btools/routingapp/ConfigMigration.java, brouter-routing-app/src/main/java/btools/routingapp/CoordinateReader.java, brouter-routing-app/src/main/java/btools/routingapp/CoordinateReaderInternal.java, brouter-routing-app/src/main/java/btools/routingapp/CoordinateReaderLocus.java, brouter-routing-app/src/main/java/btools/routingapp/CoordinateReaderOrux.java, brouter-routing-app/src/main/java/btools/routingapp/CoordinateReaderOsmAnd.java, brouter-routing-app/src/main/java/btools/routingapp/DownloadService.java, brouter-routing-app/src/main/java/btools/routingapp/NotificationHelper.java, brouter-routing-app/src/main/java/btools/routingapp/ServiceModeConfig.java, brouter-routing-app/src/main/java/btools/routingapp/WpDatabaseScanner.java
I know that in #345 I stated that mass reformatting should be avoided and only parts which are changed should be reformatted. But working on some code changed my mind because I could not use the Android Studio formatting feature for some files (e.g. `BRouterService.java`) without having a huge diff when changing only a single line.
I've used the default Android Studio settings and only reformatted the Java files in `brouter-routing-app`. If you want any other style we could extend the `.editorconfig` and I'll rerun the reformatting again.
While this PR is rather big it doesn't change any functionality but just reformats the code.
Since Git 2.23 there's an option to ignore commits during blame so despite the refactoring the output of `git blame` should still be sensible. Unfortunately …
=> Reformat using Android Studio

misc/profiles2/fastbike.brf
=> fastbike: Check isunpaved for highway=unclassified

brouter-core/src/main/java/btools/router/RoutingContext.java
With turnrestrictions on in footmode we get a wrong route:
https://github.com/nrenner/brouter-web/issues/469
=> no turnrestrictions for footmode

brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java
Made changes for issue #399 points 2. and 3.
=> trackdir and brouter.redirect changes

misc/profiles2/rail.brf
=> Use more railway lines for routing

brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl, brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java
To get same results for nogo lines and areas both (server and Android version) should use same routine. So I removed some test code.
=> Repair BRouterWorker

brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java, brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java
* Fixup to #413 which shows more information in case of download error
* Fixup to #431 to restore unpacking readmes
=> Minor fixes to DownloadWorker and setup

docs/Gemfile, docs/Gemfile.lock
dependabot noticed another dependency with security issues (#461), but lets just update all dependencies.
=> Update jekyll/gh-pages dependencies

docs/features/vianogo.md
=> Link from vianogo to android docs

.editorconfig, brouter-core/src/main/java/btools/router/OsmNodeNamed.java, brouter-mapaccess/src/main/java/btools/mapaccess/MatchedWaypoint.java, brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl, brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java, brouter-server/src/main/java/btools/server/RouteServer.java, brouter-server/src/main/java/btools/server/request/ServerHandler.java
At #441 we talked about splitting the big update into smaller ones to have a better overview.
This is the first part with 'only' interface changes. It has no new results, routines for using it will follow.
=> Update lib part one - interface

brouter-expressions/src/main/java/btools/expressions/IntegrityCheckProfile.java, brouter-expressions/src/test/java/btools/expressions/IntegrityCheckProfileTest.java, misc/profiles2/softaccess.brf
As discussed in #458 I add a test for profiles against the current lookup.dat
And a command line test version as well
=> Add test profiles with lookups.dat

brouter-core/src/main/java/btools/router/RoutingContext.java, brouter-core/src/main/java/btools/router/RoutingEngine.java, brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java, brouter-mapaccess/src/main/java/btools/mapaccess/NodesCache.java, brouter-mapaccess/src/main/java/btools/mapaccess/OsmNode.java, brouter-mapaccess/src/main/java/btools/mapaccess/WaypointMatcherImpl.java, brouter-server/src/test/java/btools/server/RouteServerTest.java
The main discussion is found in #441. But there are several issues about this theme. 
It uses the new parameter straight=idx,... or a mark on the parameter lonlats=lon,lat,d;... and marks always the first point of the two points we use for the straight routing. Anyway there can be more then one direct point in one route request.
=> Update lib part two - direct routing

misc/profiles2/fastbike.brf
Minor 1 char change to improve profile code readability.
=> Correc indent typo

brouter-core/src/main/java/btools/router/OsmPath.java, brouter-core/src/main/java/btools/router/OsmTrack.java, brouter-core/src/main/java/btools/router/RoutingEngine.java, brouter-core/src/main/java/btools/router/VoiceHint.java, brouter-core/src/main/java/btools/router/VoiceHintProcessor.java, docs/features/voicehints.md
The calculation for voice hints has changed and at the end of data collection a post process is done.
Changes on turn instruction are mainly discussed in #375.
The main discussion for the lib 1.6.4 is found in #441.
New output for this will follow.
=> Update lib part five - change voicehints

misc/pbfparser/OsmParser.java
To be pmd conform we need a change on the OsmParser for the pbfparser lib.
=> Use an interface call in pbfparser lib

.github/workflows/gradle.yml, brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl, brouter-server/src/main/java/btools/server/request/ServerHandler.java
Fine tuning for git actions
Update for the interfaces server and app
=> App update

misc/profiles2/fastbike-verylowtraffic.brf
=> Repair #268

misc/profiles2/mtb.brf
This is @Poutnik profile for MTB - which is not yet available in default profiles in brouter but I think it makes sense to have one?
I am using it for several years now and am pretty happy with it. Basically it is a small variant of trekking profile with prefer track/path over roads.
=> Add MTB profile

build.gradle, docs/revisions.md
Summary for changes in the next version.
=> Prepare update

brouter-core/src/main/java/btools/router/OsmPath.java, brouter-core/src/main/java/btools/router/OsmTrack.java, brouter-core/src/main/java/btools/router/RoutingEngine.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java, brouter-server/src/main/java/btools/server/request/ServerHandler.java, docs/developers/android_service.md, docs/developers/http_server.md
Some rework on the output.
Added a check for the misplaced routine to avoid funny results on roundabouts. Please see [here](https://github.com/abrensch/brouter/issues/519#issuecomment-1489940665)
Did some smaller rework on elev and energy values.
=> Lib update export

brouter-codec/src/main/java/btools/codec/MicroCache.java, brouter-core/src/main/java/btools/router/VoiceHintProcessor.java
Fix some minor spelling things I've come across by accident
=> fix some spellings

brouter-core/src/main/java/btools/router/VoiceHintProcessor.java
As reported in #545 the calculation on left-hand driving needs a little update.
And as expected, the turnInstructionRoundabouts variable should return "normal" turn-by-turn directions when set to false.
=> Rework on roundabout

brouter-routing-app/build.gradle, brouter-routing-app/src/main/AndroidManifest.xml, brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java, brouter-routing-app/src/main/java/btools/routingapp/RoutingParam.java, brouter-routing-app/src/main/java/btools/routingapp/RoutingParameterDialog.java, brouter-routing-app/src/main/java/btools/routingapp/ServerConfig.java, brouter-routing-app/src/main/java/btools/routingapp/ServiceModeConfig.java, brouter-routing-app/src/main/res/layout/dialog_message.xml, build.gradle
As suggested in #369 here a dialog to edit profile options - similar to the web client.
This can be used from inside the app with one of the six profile modes.
But it is also possible to connect from an external app to this dialog and edit the parameter from an external profile. 
The `RoutingParameterDialog` contains a small description.
=> Add an app params dialog

brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java
The Play Store has found an error in parsing integer.
=> App error in parsing int

brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java, docs/developers/android_service.md
Initialized with #585 a silent start mode for Router app is added.
=> Add a silent mode for app start

.github/workflows/gradle-publish.yml, .github/workflows/gradle.yml, brouter-core/src/main/java/btools/router/OsmTrack.java, build.gradle, docs/revisions.md
This update relates to PR #594  - reindex voicehint constants.
It also changes the git action scripts (Android bundle, java version and manual start option) - this is untested.
=> Prepare new release 1.7.2

brouter-core/src/main/java/btools/router/VoiceHintProcessor.java, brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java, brouter-routing-app/src/main/AndroidManifest.xml, brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl, brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java, brouter-routing-app/src/main/java/btools/routingapp/RoutingParameterDialog.java, brouter-routing-app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, brouter-routing-app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
For some issues there are a few minor changes:
- NullPointerException on VoiceHintProcessor #603
- NullPointerException on ServiceModeConfig, reported from Play Store
- IllegalStateException on RoutingParameterDialog, reported from Play Store
- Monochrome icon #597
=> Update the APK for multiple issues

brouter-core/src/main/java/btools/router/OsmTrack.java, brouter-routing-app/build.gradle, build.gradle, docs/revisions.md
This update relates to PR #605 - update for minor issues.
=> Prepare version number 1.7.3

brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java
Avoids recalculation of `toLowerCase()` for every branch in `addLookupValue()`
=> Replace multiple occurrences of toLowerCase()

misc/profiles2/gravel.brf
A highly customizable gravel profile that showcases almost all available features.
=> Add gravel profile

brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java, brouter-expressions/src/test/java/btools/expressions/EncodeDecodeTest.java
Update with rework as discussed in #616:
removed trim, renamed variable back to `value`, added new parse character.
=> Replace multiple occurrences of toLowerCase() - continued

docs/Gemfile.lock
dependabot already created #618 but this just updates all dependencies
=> `bundle update` docs dependencies

brouter-server/src/main/java/btools/server/BRouter.java
Remove seed logic and added file param as an alternative for CGI output.
=> Update cmd line BRouter

brouter-server/src/main/java/btools/server/RouteServer.java
There was a problem with custom profiles on the BRouter server.
=> Enabled custum profiles on server

brouter-core/src/main/java/btools/router/OsmTrack.java, brouter-core/src/main/java/btools/router/RoutingEngine.java, brouter-server/src/main/java/btools/server/BRouter.java, brouter-util/src/main/java/btools/util/CheapRuler.java
Reverts abrensch/brouter#674
This needs more testing.
Sometimes IllegalArgumentException("error re-tracking track") occurs.
=> Revert "App: Rerouting"

brouter-core/src/main/java/btools/router/OsmTrack.java, brouter-server/src/main/java/btools/server/BRouter.java
As described in the issue #657, the location of last message and last position are now the same.
Please, all users of json output should have a look at it, if this effects something on the client.
=> Last message in track

brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java, docs/revisions.md
According to issue #695, a check for the nogo list and the file size has been added.
Reason was the switch to the parameter collector.
=> Add a check for the nogo list

brouter-routing-app/src/main/java/btools/routingapp/BImportActivity.java, docs/revisions.md
In Google Play Store I found an exception report on the profile import. 
I can't provoke or test this exception, but hope this helps.
=> Prevent exceptions when importing profiles

brouter-core/src/main/java/btools/router/OsmTrack.java, brouter-routing-app/build.gradle, buildSrc/src/main/groovy/brouter.version-conventions.gradle, docs/revisions.md
Add a new version for BRouter see [changes](https://github.com/abrensch/brouter/pulls?q=is%3Apr+milestone%3A%22Version+1.7.5%22+is%3Aclosed)
=> Preparing for version 1.7.5

brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java, brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java, build.gradle, docs/revisions.md, gradle/wrapper/gradle-wrapper.properties
Some updates for gradle and the revisions doc.
=> Update gradle and docs

brouter-routing-app/src/main/res/values-zh/strings.xml
Chinese language for BRouter contributed by @Ptckh in Cruiser:
- https://github.com/devemux86/cruiser/discussions/669
=> Chinese language

brouter-core/src/main/java/btools/router/VoiceHint.java, brouter-core/src/main/java/btools/router/VoiceHintProcessor.java, brouter-server/src/main/java/btools/server/request/ServerHandler.java, misc/scripts/standalone/server.cmd, misc/scripts/standalone/server.sh
Discussion and test results please see #723
This contains also an update for ServerHandler to enable old requests
please see #710
Set an environment variable like
`export USEOLDSERVERFORMAT="yes"`
=> Rework voicehint

docs/developers/profile_developers_guide.md
Added the missing description for the start way check. Please see #728
=> Description for start way feature

brouter-routing-app/src/main/res/values-cs/strings.xml
Czech language for BRouter contributed by a Cruiser user:
- https://github.com/devemux86/cruiser/discussions/719
=> Czech language

misc/scripts/mapcreation/brouter.sql, misc/scripts/mapcreation/brouter_cfg.lua
Updated to the latest database scripts.
Thanks to @EssBee59 to prepare that.
=> Updated database scripts

brouter-core/src/main/java/btools/router/RoutingContext.java, brouter-core/src/main/java/btools/router/RoutingEngine.java, docs/developers/profile_developers_guide.md, misc/profiles2/car-vario.brf, misc/profiles2/gravel.brf, misc/profiles2/hiking-mountain.brf, misc/profiles2/moped.brf, misc/profiles2/mtb.brf, misc/profiles2/river.brf, misc/profiles2/trekking.brf
Update for #762 to enable dynamic range for all waypoint matches.
=> Change dynamic range meaning

docs/developers/algorithm.md, docs/developers/android_service.md, docs/features/vianogo.md, docs/privacy_policy.md, docs/revisions.md, docs/users/android_advanced.md, docs/users/android_quickstart.md, misc/profiles2/fastbike.brf, misc/profiles2/gravel.brf, misc/profiles2/hiking-mountain.brf, misc/profiles2/moped.brf, misc/profiles2/trekking.brf, misc/scripts/mapcreation/brouter.sql
Just a few minor wording adjustments that I noticed a while ago while browsing the codebase.
=> Fix a few typos in various files

misc/scripts/mapcreation/brouter.sql, misc/scripts/mapcreation/brouter_cfg.lua
The dabase scripts are new for the issue #771
=> Database scripts updated

brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl, docs/developers/android_service.md, docs/developers/profile_developers_guide.md, docs/revisions.md, misc/scripts/mapcreation/readme_database.md
Added new features to the docs.
=> Update for the Docs

brouter-routing-app/src/main/res/values-da/strings.xml, brouter-routing-app/src/main/res/values-pt/strings.xml, brouter-routing-app/src/main/res/values-sv/strings.xml
Danish, Portuguese, Swedish languages for BRouter.
=> Languages: Danish, Portuguese, Swedish
