abrensch/brouter

- misc/scripts/standalone/server.cmd
- misc/scripts/standalone/server.sh
I guess it makes sense to set a longer timeout (5 min) for the standalone server, a default entry also makes it easier to customize.
Could you please update the scripts in your release process, so they get included the next time.
In addition, the shell script in the release zips has Windows line breaks, not sure where this happens, but could you please convert these to Unix line endings (e.g. in an editor) after copying?
Not sure if it would make sense to automate this, e.g. using Ant.
> set default timeout in standalone scripts

- brouter-core/src/main/java/btools/router/RoutingContext.java
When used as standalone server on Windows, getting the profile name for custom profiles didn't work, and the remaining unescaped backslashes in the response lead to an JSON parsing error. See nrenner/brouter-web#53.
> Fix profile path splitting on Windows

- brouter-map-creator/src/main/java/btools/mapcreator/NodeData.java
I do not thing this is cure, but during map creation I got
Exception in thread "main" java.lang.NegativeArraySizeException
at btools.mapcreator.NodeData.<init>(NodeData.java:32)
which is strange, because array length (description.length) cannot be negative. So either description length was > 127 or ... ?
This pull request contains sanity check during serialization so description lengt cannot be bigger than 1 byte.
Also changes data format. Patch changes signed description lenght to unsigned byte. This change MAY be backward compatitble, but I did not bothered to check. I appologize for that.
> NegativeArraySizeException during map creation

- brouter-server/src/main/java/btools/server/RouteServer.java
- misc/scripts/standalone/local.sh
when running brouter in standalone mode it binds to all ip-addresses. This is fine for a real server on the internet, but for local use this is a security-issue. A software never should open ports reachable by the outside world if not explicitly required for this task.
This pull-requests adds an optional 'bindadress'-parameter. Usage see new startupscript local.sh
> add optional parameter bindaddress for standalone mode

- brouter-server/src/main/java/btools/server/RouteServer.java
- brouter-server/src/main/java/btools/server/request/ServerHandler.java
standalone mode fails if nogos are send with "|" being encoded as %7C resulting in java.lang.NumberFormatException: For input string: "300%7C12.0093".
%7C is standard url-encoding for "|" (as being defined in RFC-3986 https://tools.ietf.org/html/rfc3986#section-2.3).
This fix applies standard-based URLDecoding to the whole query-string before it is being parsed and removes the now obsolete explicit handing of %7C and %2C.
> decode query-string by standard URLDecoder

- brouter-core/pom.xml
- brouter-core/src/main/java/btools/router/OsmNogoPolygon.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/test/java/btools/router/OsmNogoPolygonTest.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java
- brouter-routing-app/src/main/java/btools/routingapp/CoordinateReaderOsmAnd.java
- brouter-server/src/main/java/btools/server/BRouter.java
- brouter-server/src/main/java/btools/server/RouteServer.java
- brouter-server/src/main/java/btools/server/request/ServerHandler.java
- pom.xml
This pull-request adds support for nogo-polygons and polylines. A nogo-polygon is being used as a nogo-area being defined by an (arbitrary shaped) polygon. A nogo-polyline is simmilar to this with the difference that the polygon is not taken as closed, so it defines a border that is not to be crossed when routing.
I currently can be utilized via the standalone server (new query-parameters 'polygons' and 'polylines') and on Android from OsmAnd (by saving tracks with the filename beginning with 'nogo').
(The web-frontend does not yet support this, but QMapshack already has full support for this feature).
> Nogo polygons / polylines

- misc/pbfparser/README.txt
- misc/scripts/mapcreation/process_pbf_planet.sh
Hi,
I was having a look at map creation and the best way to create segments on one's own and felt like this part could use a bit more documentation (especially the `pbfparser` building process which took me some time to figure out).
I reworked a bit the `pbfparser` README with a bit more detailed instructions.
Also, there seems to be a missing argument to `OsmCutter` in the `process_pbf_planet.sh` script.
That being said, the `OsmCutter` line in this script works perfectly fine for me with `bzip -dc *.osm.b2 | java …` but it does not extract any ways (nor gives any error) when I provide it with a pbf extract from https://download.geofabrik.de/. Am I missing something in the `pbfparser` build process?
Best,
> Complete doc for map creation

- brouter-core/src/main/java/btools/router/OsmNodeNamed.java
- brouter-core/src/main/java/btools/router/OsmNogoPolygon.java
- brouter-core/src/main/java/btools/router/OsmPath.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/StdPath.java
- brouter-core/src/test/java/btools/router/OsmNodeNamedTest.java
- brouter-core/src/test/java/btools/router/OsmNogoPolygonTest.java
- brouter-core/src/test/java/btools/router/RoutingContextTest.java
- brouter-mem-router/src/main/java/btools/memrouter/ScheduledRouter.java
- brouter-server/src/main/java/btools/server/request/ServerHandler.java
- brouter-util/src/main/java/btools/util/CheapRulerSingleton.java
Hi,
This PR should allow user to specify custom weights/penalty for each nogo circle. The motivation behind this is that so far the nogos are an all or nothing feature whereas they could potentially offer more control to the user by slightly biasing some areas.
Typically, in France, a lot of cities provide OpenData about road works (a full list of the files I found so far is available at https://framagit.org/phyks/cyclassist/blob/34e0fec0165d3633e1d254f360fcd8c2cdfac78c/scripts/opendata/works.py#L304-389). Some road works might be a complete road closure (nogo as currently implemented) while other might just mean having to deal with some extra pain (only some lanes closed, traffic jam expected etc). The latter ones should be avoided if possible, but not at all cost.
I tried to take care …
> Allow custom nogo weights

- brouter-core/src/main/java/btools/router/OsmNogoPolygon.java
- brouter-core/src/test/java/btools/router/OsmNogoPolygonTest.java
I think there was some potential errors for nogo polylines with a cost. This should partially fix it.
I can still think of some edge cases where the distance computation within/across a polygon/polyline could fail (typically when on the edge and then crossing a polygon). These are very particular edge cases though.
The main problem I can think of so far about these edge cases and the polylines is the fact that `intersect2D_2Segments` is making hard check against zero (lines exactly parallel) whereas in practice, there will always be some numerical residue.
> Fix nogo weights with polylines

- brouter-server/src/main/java/btools/server/request/ServerHandler.java
Hi,
After #117, nogo polygons / polylines can have a custom weight. The BRouter-server part of the code was not updated to be able to consume polygons / polylines with a custom weight. This is done in this PR.
The polylines/polygons parameter is now read two by two (for latitude and longitude pairs). If a trailing single value is available, it is considered to be the weight.
This PR also includes a fix for a bug with GeoJSON generation. When no voice hints were emitted, the comma at the end of the `cost:` line was deleted, resulting in an invalid GeoJSON file.
Best,
> Add support for nogo polygons / polylines weight in brouter server

- brouter-server/src/main/java/btools/server/request/ServerHandler.java
Hi,
It seems there was an error with not passing a nogo weight for polygons/polylines nogos in the server. Default value should be `NaN`, to make them true nogos.
Instead, the default value was 0 which means this was simply ignored.
Best,
> Fix default nogo weight for polygons

- brouter-server/src/main/java/btools/server/request/ServerHandler.java
This is a follow up of https://github.com/abrensch/brouter/pull/132, eg. when you set add a track name via query param, instead of generating `brouter-<profile>-<alternateidx>.<format>` filename, we should use the query name instead.
cc @Phyks
> Use track name param if set

- misc/scripts/standalone/server.sh
Instead of doing `cd standalone/ && sh server.sh`, one can directly do `sh standalone/server.sh`.
> Don't require server.sh to be launched from standalone directory

- brouter-server/src/main/java/btools/server/RouteServer.java
- brouter-server/src/main/java/btools/server/request/ServerHandler.java
In case filename contains spaces or anything non ascii, we have to quote the content disposition header to have it work properly.
Similarly, avoid strange characters in filename.
> Content-Disposition filename must be quoted

- .gitignore
- README.md
- misc/scripts/standalone/local.sh
- misc/scripts/standalone/server.cmd
- misc/scripts/standalone/server.sh
- Refactor/merge server.sh and local.sh
- Allow to run server.sh and server.cmd from source directory
- Update README
Test Plan:
- clone repo
- run maven
- drop rd5 into ``misc/segments4``
- launch ``./misc/scripts/standalone/server.sh``
(Note how no further configuration is necessary. In addition, compatibility with the directory structure as found in BRouter's zip archives is kept.)
> Make it easier to directly run BRouter from source checkout

- brouter-core/src/main/java/btools/router/RoutingContext.java
Hi,
Here are two commits to fix #154:
1. First commit changes the way the nogo polyline with a weight works. Past behavior was to have a cost given by `nogoCost * distance_travelled_along_the_line`. However, a polyline will almost never match with the routing linestring, so the resulting cost is actually `0` most of the time. It makes more sense in my opinion to have nogo polylines add a constant penalty whenever they are crossed, to "cut out" streets. I'm very much open to feedback and discussion on this change.
2. The second commit addresses #154. Basically, there was an incorrect handling of the `nogoCost` in the default case (no specific cost given, ignore the nogo area completely), which resulted in polylines and polygons being handled as circles (therefore without any precise check …
> Fix polygon/polyline nogos issues (#154)

- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-server/src/main/java/btools/server/request/ServerHandler.java
Hi,
This PR aims at solving https://github.com/abrensch/brouter/issues/91 by introducing a new `exportWaypoints` parameter in the server handler.
Typical implementation so far is:
```
curl "http://127.0.0.1:17777/brouter?lonlats=2.297409,48.873226|2.296593,48.873897|2.296014,48.873812&profile=trekking&alternativeidx=0&format=geojson&exportWaypoints=1"
```
```json
{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {
"creator": "BRouter-1.1",
"name": "brouter_trekking_0",
"track-length": "221",
"filtered ascend": "0",
"plain-ascend": "-3",
"total-time": "32",
"total-energy": "2122",
"cost": "651",
"messages": [
["Longitude", "Latitude", "Elevation", "Distance", "CostPerKm", "ElevCost", "TurnCost", "NodeCost", "InitialCost", "WayTags", "NodeTags"],
["2297244", …
```
> Export waypoints in formatted tracks

- misc/profiles2/car-eco-suspect_scan.brf
- misc/profiles2/car-eco.brf
- misc/profiles2/car-fast.brf
- misc/profiles2/car-traffic_analysis.brf
- misc/profiles2/car-vario.brf
- misc/profiles2/fastbike-asia-pacific.brf
- misc/profiles2/fastbike-lowtraffic.brf
- misc/profiles2/fastbike.brf
- misc/profiles2/lookups.dat
- misc/profiles2/moped.brf
- misc/profiles2/shortest.brf
- misc/profiles2/trekking.brf
- misc/profiles2/vm-forum-liegerad-schnell.brf
- misc/profiles2/vm-forum-velomobil-schnell.brf
Hi,
This should address #166 and #174 (one commit for each):
1. I updated the profiles so that `living_street=yes` is equivalent to `highway=living_street`.
One might argue that `living_street=yes` should have a slight penalty with respect to `highway=living_street` to reflect that this might not be fully a living street (`highway=secondary` + `living_street=yes` probably means there is much traffic and one can expect this to be a poor quality living street). I, however, don't have enough feedback so far on the use of `living_street` across the world (seems to be mostly used in Russia so far), so I think considering it as an alias is fine for a first version.
2. I added support for `sidewalk:bicycle` tag (and its `left`/`right` variants). This one is mainly used in Germany to describe an …
> Add new lookups

- misc/readmes/profile_developers_guide.txt
as i wanted to read through the guide anyway, i took the opportunity for fixing typos.
the diff on github looks a bit bigger than the real difference.
> profile developers guide: fix typos and whitespace

- misc/profiles2/.gitignore
Ignore profiles in Git that are generated by [misc/scripts/generate_profile_variants.sh](https://github.com/abrensch/brouter/blob/master/misc/scripts/generate_profile_variants.sh).
> Ignore generated profiles

- misc/scripts/generate_profile_variants.sh
`/usr/bin/sh` is not found on Ubuntu 18.04, suggesting to use `/bin/sh` instead.
> Fix shell in generate_profile_variants.sh

- brouter-server/src/main/java/btools/server/RouteServer.java
* return specific http codes for errors
* do not terminate old thread when threads limit reached
Original implementation of the thread pool was limiting max number of
threads by terminating oldest thread if the limit was already reached and
a new request has arrived. This was causing broken responses under load.
Instead we now wait until one of the threads completes before starting a
new one.
> Improve http server

- misc/profiles2/fastbike-verylowtraffic.brf
- misc/profiles2/fastbike.brf
- misc/profiles2/hiking-beta.brf
- misc/profiles2/moped.brf
- misc/profiles2/shortest.brf
- misc/profiles2/trekking.brf
- misc/profiles2/vm-forum-liegerad-schnell.brf
- misc/profiles2/vm-forum-velomobil-schnell.brf
If BRouter calculates a route with a cycling or hiking profile,
the `smoothness` tag is included in the response. That enables
a statistical analysis for the calculated route (distribution of
smoothness tags by distance).
See the analysis sidebar at https://brouter.m11n.de/ for an example.
References: 
- #249 
- nrenner/brouter-web#45
> add `dummyUsage` to certain profiles

- brouter-core/src/main/java/btools/router/OsmTrack.java
Extends the already existing `voicehints` property in the GeoJSON format with the remaining values to pass full voice hint information to the client.
Also adds a new `times` property with all node time values. The GeoJSON spec explicitly does not allow additional values in the coordinates array anymore, so the times are passed as a separate array in properties that corresponds with the coordinates array. This will allow to e.g. [plot elevation over time rather than distance](https://groups.google.com/g/osm-android-bikerouting/c/u4K6RTmhzhI/m/oDAXHE_vBQAJ) and adding [time tags to GPX](https://github.com/abrensch/brouter/issues/221) (also [brouter-web#196](https://github.com/nrenner/brouter-web/issues/196)), voice hint times are looked up by `indexInTrack`.
The background is to enable …
> Complete voice hints and add times to GeoJSON

- brouter-core/src/main/java/btools/router/MessageData.java
- brouter-core/src/main/java/btools/router/OsmTrack.java
The purpose of this little change is to include time and energy in messages used for voice hints generation. This is meant to allow clients: 1) indicate time to the next voice hint (manoeuvre), 2) (Our interest) Greatly improve the way Locus handles ETA of planned tracks.
> Added time and energy to response messages.

- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-core/src/main/java/btools/router/RoutingHelper.java
- brouter-mapaccess/src/main/java/btools/mapaccess/NodesCache.java
- brouter-mapaccess/src/main/java/btools/mapaccess/StorageConfigHelper.java
- brouter-routing-app/build.gradle
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerView.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java
- brouter-routing-app/src/main/java/btools/routingapp/ConfigHelper.java
- brouter-routing-app/src/main/java/btools/routingapp/ConfigMigration.java
- brouter-routing-app/src/main/java/btools/routingapp/CoordinateReader.java
- brouter-server/src/main/java/btools/server/BRouter.java
- brouter-server/src/main/java/btools/server/RouteServer.java
- brouter-server/src/main/java/btools/server/ServiceContext.java
- brouter-server/src/test/java/btools/server/RouterTest.java
I wanted to clean up the definition / access of the brouter base directory to be more aligned with Android's storage model - particularly, directly using `Context.getExternalFilesDirs` to find writable directories without manually constructing any paths. Effectively, the paths presented in the path selection dialog should always work. For the manual path entry, I added the capability to request the `WRITE_EXTERNAL_STORAGE` permission, so that more paths can be selected. Unfortunately, this still doesn't allow us to write to the actual SD card outside of the app-specific `Android` directory, but _does_ allow directly writing to `/storage/emulated/0` if the user wishes to. I also did some general clean-up, using `java.io.File` instead of just `String` in some places, and also …
> Cleanup file / base directory access

- README.md
- brouter-map-creator/build.gradle
- brouter-routing-app/build.gradle
- brouter-server/build.gradle
- build.gradle
- settings.gradle
Removed the error message when no Android SDK is defined.
Add only one version code in main gradle file for all sub projects.
> Migrate to gradle part 3

- .gitignore
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java
- brouter-routing-app/src/main/AndroidManifest.xml
- brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl
- brouter-routing-app/src/main/java/btools/routingapp/AppLogger.java
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerView.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java
- brouter-routing-app/src/main/java/btools/routingapp/CoordinateReaderInternal.java
- brouter-routing-app/src/main/java/btools/routingapp/CoordinateReaderLocus.java
- brouter-routing-app/src/main/java/btools/routingapp/CoordinateReaderOrux.java
This update has some parts for the move to Android 11
- change the inferface #314
- change main folder .../Android/media/btools.routingapp/
- has an own import folder for files like favorites or nogo* gpx
- export json #246
- update all tiles #306
- hardcoded speed #301
- black screen #286
still pending
- new icon brouter-web [286](https://github.com/nrenner/brouter-web/issues/286)
- refreshed profiles
- Android watchdog #277 - no error results during testing
- download manager #271 - no error results during testing
- download rd5 in background #227
- update for lookups.dat and profiles over the air
others
- git workflow: is there someone how can do the move to gradle? I've never done it and doesn't have a test environment.
This version is based on the idea other apps use the interface …
> Update for Android 11 part 1

- .github/workflows/gradle.yml
- brouter-server/build.gradle
To simplify testing the result of each build is attached as an artifact to the workflow run.
It seems like the GitHub runners have the android SDK installed so it's possible to provide the APKs in addition to the brouter.zip. The GitHub UI is a bit [quirky](https://github.com/actions/upload-artifact/issues/3#issuecomment-743985727) and the brouter.zip download is zipped again before the download.
> GitHub Workflow: Provide Artifacts (APK & ZIP)

- brouter-server/build.gradle
Enable the pure run of the jar file. 
Like:
`
$java -jar brouter-1.6.2-all.jar
`
Add a dependsOn to remove some warnings.
> change manifest, add dependson

- brouter-routing-app/src/main/AndroidManifest.xml
When updating from a previous app which has it's basedir on e.g.
/sdcard/emulated/0/brouter it's still possible to access the files on
android 11 with this flag.
> Set preserveLegacyExternalStorage for easier upgrades

- misc/profiles2/fastbike.brf
- misc/profiles2/trekking.brf
add "sett" as a paved surface (often nicer for bikes than paving_stones)
otherwise, sett surfaces tend to be avoided in routing, while it is usually smooth
even for thin wheels
> Consider sett as paved in trekking.brf & fastbike.brf

- brouter-routing-app/build.gradle
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerView.java
- brouter-routing-app/src/main/java/btools/routingapp/DownloadService.java
- brouter-routing-app/src/main/res/layout/activity_binstaller.xml
- brouter-routing-app/src/main/res/values/strings.xml
Currently DownloadManager has most of the logic in `BInstallerView`. This includes showing segment selection and download progress. Views should only be used for displaying information, not general logic like deleting files etc.
I've moved most logic `BInstallerActivity` and used layouts to show information/button and download progress.
- Replaced custom touch event handling with `GestureDetector` and `ScaleGestureDetector`
- Avoid moving map out of bounds
- Simplify drawing code
> Use layouts in DownloadManager

- brouter-core/src/main/java/btools/router/OsmTrack.java
I saw https://groups.google.com/g/osm-android-bikerouting/c/htEAGAOsBkc coming by and had a look at the details.
I could reproduce the XML validation problem using Renner_original.gpx but by adding http://www.garmin.com/xmlschemas/GpxExtensions/v3 as schema that problem is gone
> Update locus xml generation to have only one extension section

- brouter-server/build.gradle
After merging #439 only a single APK is provided which wasn't part of the provided zip.
Thanks @afischerdev for the fix
> Update APK path

- build.gradle
- config/checkstyle/checkstyle.xml
- config/checkstyle/suppressions.xml
As [suggested by @nrenner](https://github.com/abrensch/brouter/pull/441#issuecomment-1179185729) it's helpful to check code formatting automatically.
It seems for java [checkstyle](https://checkstyle.sourceforge.io/) is the usual way. Unfortunately our current codebase has a mixture of tabs and spaces and also mixed indentation which would cause build failures when enabling the checks. Therefore I've just added the configuration/integration but suppressed any results until we fix those issues.
We could manually fix those issues or do a mass reformat similar to #368. For #368 I used the default codestyle from Android Studio because I assumed that's what most people use for android development. As we now want to reformat the whole codebase we need to decide if we want this codestyle for …
> Automatically check codestyle using checkstyle

- docs/users/android_advanced.md
- docs/users/android_quickstart.md
The app specific coordinate readers were removed in #439 but documentation wasn't updated.
I've cherry-picked the changes from @afischerdev's `avoid-peaks` branch
> Update docs after coordinate reader removal

- misc/profiles2/river.brf
Add support for routing over fairways which are used for navigable routes in a body of water
(where waterway=river or waterway=canal are not appropriate).
---
The current river profile works fine for (water)ways which are tagged with waterway=river or waterway=canal, but not for  waterway=fairway ([OSM  wiki](https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dfairway)).
Example where routing does not work with the current profile, but where this change gives the desired result: 
http://brouter.de/brouter-web/#map=13/52.9304/5.6102/standard&lonlats=5.630567,52.936295;5.641656,52.899167&profile=river
This supports boat and canoe routing just as  #202, but concerns navigating over linear features in OSM instead of navigating over  bodies of water which do not have linear waterway features in …
> Update river profile

- .editorconfig
- brouter-core/src/test/java/btools/router/OsmNogoPolygonTest.java
- brouter-routing-app/build.gradle
- brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java
- config/checkstyle/checkstyle.xml
The gradle checkstyle plugin works only for modules which use the `java` or `java-library` plugin. The use checkstyle also for our android app gradle needs some additional setup.
In addition I've added some more checkstyle rules which enforce whitespace handling according to our style after reformatting.
> Enable checkstyle for brouter-routing-app

- brouter-core/src/main/java/btools/router/StdPath.java
The combination of bd02587 and 57da34d causes a bug in the travel time calculation in the kinematic model, which can lead to a significant miscalculation in certain cases:
| Old | New |
| :---: | :---: |
| ![old](https://user-images.githubusercontent.com/122357328/211588739-1cc59ccb-52a2-49fa-902f-165e9245d3b0.jpg) | ![new](https://user-images.githubusercontent.com/122357328/211588761-df89419c-ea82-4ffe-a0ed-b54f4bf6bc13.jpg) |
Example: https://brouter.de/brouter-web/#map=12/51.8281/10.7136/standard&lonlats=10.789197,51.839793;10.636347,51.816129;10.618328,51.799937&profile=fastbike
___
This pull request fixes the bug by removing the [seemingly undocumented behavior](https://brouter.de/brouter/profile_developers_guide.txt) of falling back into hiking mode (at a walking speed equal to the …
> Fix regression of travel time calculation

- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java
- brouter-server/src/test/java/btools/server/RouteServerTest.java
This small routines recalculate the end/start of two tracks to avoid misplaced via points 
Max step go back in track is 10. 
There is also a user defined value for the distance to a misplaced via point. Default is zero - means all distance is used. Or you define e.g. 20 meters of distance so only inside 20 m the via point is removed.
If the via point is not misplaced the call can be done by adding a name to the via point. E.g.:
`8.708678,49.999188;8.71145,49.999761,stop here;8.715801,50.00065`
The output at the moment is not fully correct - the routines for re-calculation follow later on, just to keep it small.
The main discussion is found in #441.
> Update lib part three - ignore misplaced via points

- brouter-core/src/main/java/btools/router/OsmPathElement.java
- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-mapaccess/src/main/java/btools/mapaccess/MatchedWaypoint.java
- brouter-server/src/test/java/btools/server/RouteServerTest.java
The calculation for voice hints and speed profile is moved to the end of track generation. 
This only effects tracks with more then two points.
And a recalculation is done for elevation data and track distances.
The output at the moment is not fully correct - the routines for voice hints will follow.
The main discussion is found in #441.
> Update lib part four - recalculation at end of track

- brouter-core/src/main/java/btools/router/RoutingEngine.java
25e506d changed the order in which the elevation deltas are passed through the elevation filter, which can lead to the undesirable behavior that appending segments to the end of a route can decrease the calculated total ascent. This fixes the bug by adjusting the elevation filter accordingly.
> Fix regression in elevation filter logic

- brouter-core/src/main/java/btools/router/OsmPathElement.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-mapaccess/src/main/java/btools/mapaccess/OsmNode.java
The way BRouter rounds floating-point numbers to integers in the calcDistance function introduces a round-off error accumulation that increases as the average distance between two nodes decreases. This bug caught me completely off guard when I first started working with BRouter.
Here is a comparison of the total distance error distributions of 100k random routes before and after fixing the bug:
Nürburgring Sprint course:
- https://www.openstreetmap.org/way/27852990:
- ![sprintcourse](https://user-images.githubusercontent.com/122357328/213422742-ef8aea9e-04ce-4962-9b3b-47e2508d2d08.jpg)
- [https://brouter.de/brouter-web/#map=16/50.3330/6.9438/standard...&profile=shortest](https://brouter.de/brouter-web/#map=16/50.3330/6.9438/standard&lonlats=6.938351,50.329227;6.946246,50.337144;6.946105,50 …
> Fix rounding error in calcDistance

- brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java
- brouter-routing-app/src/main/java/btools/routingapp/ServerConfig.java
The file 'serverconfig.txt' holds the url and profile list for online updates.
This should be  overridden when the list of profiles changes.
When the server urls are different nothing is replaced. E.g. when a user has its own tile server.
> App update: control update for serverconfig

- brouter-core/src/main/java/btools/router/KinematicPath.java
- brouter-core/src/main/java/btools/router/OsmPath.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-core/src/main/java/btools/router/StdPath.java
- brouter-expressions/src/main/java/btools/expressions/BExpressionContextWay.java
This pull request removes the limitation that `downhillcutoff` and `uphillcutoff` as well as `downhillcost` and `uphillcost` cannot be used in the way context. This opens up new possibilities for the use of the underlying elevation data, as the cost of positive and negative elevation meters can now be evaluated differently depending on the steepness and condition of the way in question.
This is particularly useful for gravel and mountain bike profiles:
| MTB - Old | MTB - New |
| :---: | :---: |
| ![mtb-old](https://user-images.githubusercontent.com/122357328/212549751-358ef16f-55a4-4671-90b6-5a0b555898a1.jpg) | ![mtb-new](https://user-images.githubusercontent.com/122357328/212549759-75a1a231-826e-44e2-bedd-e05e2398cd33.jpg) |
Example: …
> Allow hill cost and hill cutoff in way context

- brouter-core/src/main/java/btools/router/RoutingContext.java
A route should not enter a strict nogo area. So when a via point is inside a nogo it is ignore for routing.
But if the nogo area is not strict it can be used to mark the prefered way. 
Do not remove wpt in weighted nogos.
[sample](https://brouter.de/brouter-web/#map=15/48.1869/11.5579/standard&lonlats=11.568968,48.191611;11.565835,48.187405;11.57019,48.179681&nogos=11.566286,48.18704,100;11.57264,48.187377,100,1) Please play with the values in url e.g nogos=11.566286,48.18704,100,2;11.57264,48.187377,100,1
> Fix wpt and nogo handling

- brouter-routing-app/src/main/AndroidManifest.xml
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java
The updatable tiles are displayed in grey color. When you have downloaded/updated a tile it is displayed in blue. But the 'update all' button shows al installed tiles.
New flag in manifest to keep the local data when app is deleted. 
New installed app then uses direct the 'old' data in ./Android/media/btools.routingapp/...
> App update: Show only updatable tiles

- misc/profiles2/fastbike-verylowtraffic.brf
- misc/profiles2/fastbike.brf
- misc/profiles2/trekking.brf
Avoids discarding some fine ways during routing
> Consider cycleway:left&right in onewaypenalty

- misc/profiles2/fastbike.brf
- misc/profiles2/trekking.brf
Some bicycle routes can have portions which are not accessible.
Potential reasons for this:
- temporary construction work on the ways (sometimes for months),
- local access change without simultaneous update of bicycle route relation
(lack of mapper's knowledge or lack of time to redefine an updated route),  
- ... 
This branch changes fastbike & trekking profiles so that being on a cycle 
route does not automatically mean "access granted" for bicycles. The normal 
access checkings are used instead.
However, the accesspenalty is set to 15 if the no-access way belongs to such a 
route, so that the way is not completely forbidden if there is no other 
alternative unavailable.
> Remove cycleroute always having access granted

- brouter-expressions/src/main/java/btools/expressions/BExpressionMetaData.java
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java
- brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java
According to @polyscias [update lookups comment](https://github.com/abrensch/brouter/pull/458#issuecomment-1399432466) a app version check is added.
Rework of the handling if profile param is used.
> App version check

- brouter-core/src/main/java/btools/router/RoutingEngine.java
The new code is functionally equivalent.
> Cleanup recalcTrack

- brouter-codec/src/main/java/btools/codec/MicroCache.java
- brouter-codec/src/main/java/btools/codec/MicroCache2.java
- brouter-codec/src/main/java/btools/codec/StatCoderContext.java
- brouter-core/src/main/java/btools/router/KinematicPath.java
- brouter-core/src/main/java/btools/router/OsmNogoPolygon.java
- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-core/src/main/java/btools/router/VoiceHintProcessor.java
- brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java
- brouter-expressions/src/main/java/btools/expressions/BExpressionMetaData.java
- brouter-map-creator/src/main/java/btools/mapcreator/OsmNodeP.java
- brouter-mapaccess/src/main/java/btools/mapaccess/DirectWeaver.java
- brouter-mapaccess/src/main/java/btools/mapaccess/GeometryDecoder.java
- brouter-mapaccess/src/main/java/btools/mapaccess/NodesCache.java
- brouter-mapaccess/src/main/java/btools/mapaccess/OsmNode.java
- brouter-mapaccess/src/main/java/btools/mapaccess/OsmNodesMap.java
- brouter-mapaccess/src/main/java/btools/mapaccess/PhysicalFile.java
- brouter-server/src/main/java/btools/server/BRouter.java
- brouter-server/src/main/java/btools/server/RouteServer.java
- brouter-server/src/main/java/btools/server/SuspectManager.java
- brouter-util/src/main/java/btools/util/BitCoderContext.java
- brouter-util/src/main/java/btools/util/ByteDataWriter.java
- brouter-util/src/main/java/btools/util/CompactLongMap.java
- brouter-util/src/main/java/btools/util/CompactLongSet.java
- brouter-util/src/main/java/btools/util/MixCoderDataInputStream.java
- brouter-util/src/main/java/btools/util/SortedHeap.java
- misc/pbfparser/BPbfBlobDecoder.java
Normally `BRouter` source formats opening blocks with having the curly bracket in the same line.
Somehow the reformat done between v1.6.3 and v1.7.0 did not work for opening lines having a line comment - for those blocks the opening curly bracket remained on a separate line.
This PR fixes / unifies this by moving the opening curly brackets into the blocks' opening lines.
> Unify brackets for opening blocks with comments

- brouter-map-creator/src/main/java/btools/mapcreator/ConvertLidarTile.java
- brouter-map-creator/src/main/java/btools/mapcreator/HgtReader.java
- brouter-map-creator/src/main/java/btools/mapcreator/PosUnifier.java
According to the #539 idea here a first version of a hgt reader.
It uses plain hgt or zip with hgt inside.
The PosUnifier has a test routine for single elevations.
I tested with Iceland (is West and above 60 degree).
> Add a hgt Reader

- docs/Gemfile.lock
Old bundler version caused issues at least on Ubuntu 22.04.
> Update bundle & bundler

- brouter-map-creator/src/main/java/btools/mapcreator/ConvertLidarTile.java
- brouter-map-creator/src/main/java/btools/mapcreator/OsmCutter.java
- brouter-map-creator/src/main/java/btools/mapcreator/OsmFastCutter.java
- brouter-map-creator/src/main/java/btools/mapcreator/PosUnifier.java
- brouter-map-creator/src/test/java/btools/mapcreator/MapcreatorTest.java
- misc/scripts/mapcreation/brouter.sql
- misc/scripts/mapcreation/brouter_cfg.lua
- misc/scripts/mapcreation/lookups_db.dat
- misc/scripts/mapcreation/readme_database.md
This is according to discussion #486 and adds tags via database call to the way generation.
New is 
forest to find nice ways in or near forest
river to file ways along water
noise to avoid bigger streets
town to avoid bigger citys
traffic was used before but is now generated by database call
The classpath in generation needs a jdbc driver
and the OsmFastCutter a call with some database parameter
Please see readme.
There is also a new lookups.dat that contains the new tags - before the node context. This should be neutral to older versions. 
In the next generation lookups.dat (#458) I would prefer these new tags more moved up to get smaller rd5 files.
This needs also an update for the profiles to make use of the new tags.
> Add jdbc import

- brouter-core/src/main/java/btools/router/ProfileCache.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-expressions/src/main/java/btools/expressions/BExpression.java
- brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java
- brouter-expressions/src/main/java/btools/expressions/ProfileComparator.java
- brouter-expressions/src/test/java/btools/expressions/ConstantOptimizerTest.java
- brouter-expressions/src/test/resources/profile_test.brf
This is the patch for the corresponding issue https://github.com/abrensch/brouter/issues/566
It improves the handling of constant expressions in the profile compiler
Visible effect should be that tags that are unused by configuration (e.g. estimated_forest_class) do not appear in the table if process_unused_tags=false
Tested so far via the unit tests only.
Unit tests had found a problem with injected key-values so I had to change the handling of these. An Injected value is now injected as a Number-Expression-Operand of the assign-expression that assigns the variable.
> optimizing constant expressions in profile parsing

- brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java
The update (same major version) for the lookups.dat is not replaced, when there is only a partly tiles download. Issue #580
> Fixed error in single download

- brouter-routing-app/src/main/AndroidManifest.xml
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerView.java
Based on issue #551, the download view can now also be loaded in portrait mode.
This is only possible once at the beginning. Cannot switch while in use.
> Add portrait mode to app

- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-mapaccess/src/main/java/btools/mapaccess/NodesCache.java
According to issue #568 two changes for get better results on long distances around searching points.
1. Do a second round when a way point is not found to get all square around the search square
2. Add a greater difference value for a finishing check (rc.waypointCatchingRange wasn't enough)
A 3rd idea is drop for now - tile generation: add pseudo points when no points in an areas.
> Find matching points in areas with longer distance between way points

- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-routing-app/build.gradle
- build.gradle
For the next changes I made an update on the version number to  **1.7.2-beta-1**
> Update to new beta version

- misc/scripts/mapcreation/brouter.sql
- misc/scripts/mapcreation/brouter_cfg.lua
The latest scripts for db generation in new formatting.
> Latest scripts for database generation

- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-core/src/main/java/btools/router/RoutingParamCollector.java
- brouter-core/src/test/java/btools/router/RouteParamTest.java
- brouter-server/src/main/java/btools/server/BRouter.java
The old BRouter class was working with two positions only. Now it can be called with all available routing options like:
```
java -jar brouter.jar <segmentdir> <profiledir> <engineMode> <profile> <lonlats-list> [parameter-list] [profile-parameter-list] 
or
java -cp %CLASSPATH% btools.server.BRouter <segmentdir>> <profiledir> <engineMode> <profile> <lonlats-list> [parameter-list] [profile-parameter-list]
or
java -jar brouter.jar <segmentdir> <profiledir> <parameter-list>
```
The also included 'seed' variant is not changed and should run as before. 
The new BRouter class comes with a first version of a parameter collector. The idea behind is that BRouter has three variants of parameter collection: BRouter command line, Android app and server. The new collector class should work for all. At …
> New BRouter command line with new parameter collector

- docs/Gemfile
- docs/Gemfile.lock
- docs/_README.md
- docs/developers/environmental_considerations_and_pseudo_tags.md
I'm trying to finally get the docs/website into production deployment and jekyll wasn't happy with the newly added documentation on pseudo tags. I've removed the `consider_` wording because it's specific to profiles and not the tags contained in the rd5 files.
In addition there's some notes how to preview the website locally.
> Rework pseudo tags docs

- brouter-routing-app/build.gradle
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java
- brouter-routing-app/src/main/res/values-ar/strings.xml
- brouter-routing-app/src/main/res/values-ca/strings.xml
- brouter-routing-app/src/main/res/values-de/strings.xml
- brouter-routing-app/src/main/res/values-el/strings.xml
- brouter-routing-app/src/main/res/values-es/strings.xml
- brouter-routing-app/src/main/res/values-fr/strings.xml
- brouter-routing-app/src/main/res/values-it/strings.xml
- brouter-routing-app/src/main/res/values-nl/strings.xml
- brouter-routing-app/src/main/res/values-pl/strings.xml
- brouter-routing-app/src/main/res/values/donottranslate-strings.xml
- brouter-routing-app/src/main/res/values/strings.xml
- English, Arabic, Catalan, Dutch, French, German, Greek, Italian, Polish, Spanish
- Move fixed strings to donottranslate-strings.xml
- Remove unused strings
- Enable app localization
There are several texts in the code that can be moved to strings.xml and translated as well.
The translations were contributed by Cruiser users:
- https://github.com/devemux86/cruiser/discussions/382
> BRouter translations

- brouter-routing-app/src/main/java/btools/routingapp/BInstallerView.java
BRouter download manager does not show the grid on older Android.
The reason seems to be that the `y` parameters are passed in wrong order in `Canvas.drawRect`.
They are "left, top, right, bottom" where we usually expect left < right and top < bottom.
The left < right are correct, but currently the top > bottom with no rectangles showing.
If we reverse them, then the rectangles appear again on older Android.
Newer Android works because it may reorder the parameters internally.
> Fix Canvas.drawRect on older Android

- brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java
- brouter-routing-app/src/main/java/btools/routingapp/RoutingParameterDialog.java
According to the issue #643 a change in the back pressed handling for the `RoutingParameterDialog`.
Additional:
- compressed output only for gpx and json. Otherwise an error message also comes compressed
- in app the parameter `profile` is used outside the standard parameter setting in `RoutingParamCollector`. So it is better to remove it.
> App: some error handling

- brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java
- brouter-routing-app/src/main/res/values-ar/strings.xml
- brouter-routing-app/src/main/res/values-ca/strings.xml
- brouter-routing-app/src/main/res/values-de/strings.xml
- brouter-routing-app/src/main/res/values-el/strings.xml
- brouter-routing-app/src/main/res/values-es/strings.xml
- brouter-routing-app/src/main/res/values-fr/strings.xml
- brouter-routing-app/src/main/res/values-it/strings.xml
- brouter-routing-app/src/main/res/values-ko/strings.xml
- brouter-routing-app/src/main/res/values-nl/strings.xml
- brouter-routing-app/src/main/res/values-pl/strings.xml
- brouter-routing-app/src/main/res/values/strings.xml
Moved more hardcoded strings to resource.
Initial pull request was #645
Please note: this contains no translations.
> App: Added more strings in resources

- brouter-routing-app/src/main/AndroidManifest.xml
- brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java
When BRouter app uses `targetSdk 34` some changes are needed.
This pull request contains the changes for the download manager.
- Declare [foreground service type](https://developer.android.com/about/versions/14/changes/fgs-types-required)(s) in your manifest. You must do this for each foreground service you intend to use.
- If applicable to the type selected, declare and request the [foreground service permission](https://developer.android.com/about/versions/14/changes/fgs-types-required#permission-for-fgs-type) that is appropriate for each foreground service type.
---
Documentation: https://support.google.com/googleplay/android-developer/answer/13392821
When your apps target Android 14 and above, you’ll need to declare any foreground service types that you use in a new declaration on the …
> Android targetSdk 34

- brouter-mapaccess/src/main/java/btools/mapaccess/WaypointMatcherImpl.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java
- brouter-util/src/main/java/btools/util/CompactLongMap.java
- brouter-util/src/main/java/btools/util/SortedHeap.java
During Android **release** builds with latest Android / Gradle, there are warnings and a compile error.
- The warnings are "unchecked" and "deprecation", we can suppress them,
or don't know if you want to handle them differently to have a clean build without warnings.
- More serious is the compile error at `Comparator` creation in `WaypointMatcherImpl`
Please see the pull request for the relevant sections in the code.
> Fix compile and Lint issues

- brouter-core/src/main/java/btools/router/StdPath.java
- brouter-expressions/src/main/java/btools/expressions/BExpression.java
- brouter-expressions/src/main/java/btools/expressions/BExpressionContextWay.java
- docs/developers/profile_developers_guide.md
To extend the functionality an additional "DIV" command and two additional parameters are defined. An example instance can be tested under [Brouter-Web Dev Instance](https://brouter.densborn.ddnss.de/) with [fastbike-longdistance.brf](https://github.com/simdens/brouter_profile) profile. 
"DIV" command:
The profile can compute constants within the global context based on physical values like systemweight or nominal power.
"downhillmaxbuffercost" and "uphillmaxbuffercost"
These parameters allow to increase the uphill or downhill penalty if the buffer exceeds the maximum buffer value. This makes it possible to increase the penalty for very step hills. i.e. for uphills which are too steep for the given gear ratio. See the [fastbike-longdistance.brf](https://github.com/simdens/brouter_profile) …
> Add "DIVIDE" command and new "maxslope" and "maxslopecost" parameters

- brouter-core/src/main/java/btools/router/OsmTrack.java
Do not throw an exception as it is already handled by the returned null result.
For details see #671.
> Error reading rawTrack: do not throw exception, fix #671

- brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java
Based on #676, here is an update for the certificate problem
> App: certificate fallback

- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-routing-app/build.gradle
- build.gradle
- docs/revisions.md
There are some finished issues. Please [see](https://github.com/abrensch/brouter/pulls?q=is%3Apr+milestone%3A%22Version+1.7.4%22+is%3Aclosed)
> Preparing for  version 1.7.4

- .github/workflows/docker-publish.yml
It's quite common to publish docker images because users could avoid building. It also helps to keep the Dockerfile in a working state.
> Publish docker images

- README.md
- brouter-server/src/main/java/btools/server/RouteServer.java
This fixes #699.
**Warning:** this change breaks with backward compatibility, e.g. for log parsing tool chains.
> ISO8601 compatible timestamps in log output

- brouter-server/src/main/java/btools/server/request/ServerHandler.java
The MIME type for GeoJSON registered with IANA is application/geo+json, replacing the old value application/vnd.geo+json. The change was published with RFC 7946 in 2016.
Example request:
`GET /brouter?lonlats=13.377485,52.516247%7C13.351221,52.515004&profile=trekking&alternativeidx=0&format=geojson HTTP/1.1`
Exampe response headers:
```
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Disposition: attachment; filename="brouter.geojson"
Access-Control-Allow-Origin: *
Connection: close
Content-Type: application/geo+json; charset=utf-8
```
References:
- https://www.iana.org/assignments/media-types/application/vnd.geo+json
- https://www.iana.org/assignments/media-types/application/geo+json
- https://datatracker.ietf.org/doc/html/rfc7946#section-12
> Update MIME type for GeoJSON responses

- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-routing-app/build.gradle
- brouter-routing-app/proguard-rules.pro
- buildSrc/src/main/groovy/brouter.version-conventions.gradle
- docs/revisions.md
Solved problem with car profile #712 and added a new version
> Preparing for version 1.7.6

- README.md
I've added some more information in the README.md instructions for building and running BRouter as docker container:
It probably makes it easier for others using the instructions to have the port mapping ready. Also, use an explicit name for the container instead of a randomly by docker generated one.
> Added port mapping for docker run command

- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-routing-app/build.gradle
- brouter-routing-app/src/androidTest/java/btools/routingapp/BRouterActivityTest.java
- brouter-routing-app/src/androidTest/java/btools/routingapp/DownloadWorkerTest.java
- brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java
- brouter-routing-app/src/main/java/btools/routingapp/RoutingParameterDialog.java
- brouter-routing-app/src/main/java/btools/routingapp/ServerConfig.java
- buildSrc/src/main/groovy/brouter.version-conventions.gradle
- docs/revisions.md
Google wants us to change the Android version by the end of August.
So here it comes.
This gives you the opportunity to make some additional changes that are only relevant for development:
- new versions for the libraries 
- some compiler params for better control 
- new gradle app name for compatibility with future gradle versions
- replace printstacktrace with more robust logging
> Update Android Version

- brouter-routing-app/src/main/java/btools/routingapp/BRouterActivity.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java
- brouter-routing-app/src/main/res/values-ar/strings.xml
- brouter-routing-app/src/main/res/values-ca/strings.xml
- brouter-routing-app/src/main/res/values-de/strings.xml
- brouter-routing-app/src/main/res/values-el/strings.xml
- brouter-routing-app/src/main/res/values-es/strings.xml
- brouter-routing-app/src/main/res/values-fr/strings.xml
- brouter-routing-app/src/main/res/values-it/strings.xml
- brouter-routing-app/src/main/res/values-ko/strings.xml
- brouter-routing-app/src/main/res/values-nl/strings.xml
- brouter-routing-app/src/main/res/values-pl/strings.xml
- brouter-routing-app/src/main/res/values/strings.xml
When trying to change settings for a profile that was not yet configured as a service in the android app, the app exits instead of configuring the profile. This behavior is not very intuitive for users, as it is required to first configure the profile and then open the app again to change the settings.
This change instead adds a dialog to configure the profile as a new service in case `Profile Settings` is selected and the selected profile is not yet configured as a service.
> Configure profile as service when changing profile settings

- brouter-codec/src/main/java/btools/codec/MicroCache2.java
- brouter-codec/src/main/java/btools/codec/TagValueValidator.java
- brouter-codec/src/main/java/btools/codec/WaypointMatcher.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java
- brouter-expressions/src/main/java/btools/expressions/BExpressionContextWay.java
- brouter-mapaccess/src/main/java/btools/mapaccess/DirectWeaver.java
- brouter-mapaccess/src/main/java/btools/mapaccess/WaypointMatcherImpl.java
This is the answer on the issues #600 and #682.
The idea is to place a definition for excludes highways in the profile.
This is scanned at routing start and an array is created with the index of the lookup entry and the lookup value.
The array is then used to exclude the way from the routing.
The test server is prepared for using this feature.
You have to assign a new global rule in the profile - there is no entry for this feature in the profiles at the moment.
```
assign   check_start_way          = true   # %check_start_way% | Activate a test for the starting way | boolean | noStartWay=route,ferry;highway,motorway;highway,motorway_link
```
As you see the comment part of the assign has in this case an array with 4 entries - please note, the web client can not check that at the moment, so …
> Start way check added

- brouter-core/src/main/java/btools/router/OsmTrack.java
Thanks for the remark on the code base in #733.
I can't remember why the `nodeNr` was used in the past. But I'll keep it for a while before final cleaning.
> Updated for cleaning

- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-core/src/main/java/btools/router/VoiceHintProcessor.java
As shown in issue #387 sample there is no beeline information generated when we don't have detours.
> Enable beeline voicehints when there are no detours

- brouter-core/src/main/java/btools/router/FormatGpx.java
- brouter-core/src/main/java/btools/router/FormatJson.java
- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-core/src/main/java/btools/router/VoiceHint.java
- brouter-core/src/main/java/btools/router/VoiceHintProcessor.java
- docs/features/voicehints.md
This is the PR for #734
The problem with this new voicehints is, not all clients are ready for using.
First rule: the export contains what the clients can read. Means
- Locus already has this tags of Exit Left / Right
- all other become the old values - we can change later
For testing select you favorite turnInstructionMode.
Please use for a direct test export the button between close and export.
When using JSON export you could select `turnInstructionMode = 2` to get the new index.
For OsmAnd exists a special `turnInstructionMode = 8`. This is not reachable via the profile dialog, you have to set this inside the profile editor. It can be used to prepare OsmAnd to the new voicehints before BRouter delivers the new tags on `turnInstructionMode = 3`.
A Test is possible on the test server: …
> New voicehints for motorway exit

- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-mapaccess/src/main/java/btools/mapaccess/NodesCache.java
- docs/developers/profile_developers_guide.md
- misc/profiles2/car-vario.brf
This is a follow up for PR #729
It fixes the new logic described [here](https://github.com/abrensch/brouter/pull/729#issuecomment-2541843896)
And for the car profiles an activation is possible for `track` and `road` in “Dynamic Range Mode”.
@abdullahO2
As before the results are availabe on testserver.
> Enhance dynamic range logic

- brouter-core/src/main/java/btools/router/FormatGpx.java
- brouter-core/src/main/java/btools/router/FormatJson.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl
- brouter-server/src/main/java/btools/server/BRouter.java
- docs/developers/android_service.md
The elevation function to get an elevation for a single point wasn't ready in my eyes.
Previously, only the first and last points of a segment were used. This now changes by using all segment points and searching for the nearest one.
Additionally, the routine can also provide the segment info.
It is recommended to play with the profiles to get a desired segment information.
trekking.brf
car-eco.brf
> Get elevation expanded, added get info

- brouter-core/src/main/java/btools/router/KinematicPrePath.java
From time to time there occurs a way description exception on car routing. 
But I had only one example on this - near the tile borders.
Please let us know if you find one, message text is
`null description for: n_xy
`
> Protect routing on empty way description.

- brouter-core/src/main/java/btools/router/AreaInfo.java
- brouter-core/src/main/java/btools/router/AreaReader.java
- brouter-core/src/main/java/btools/router/OsmPath.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-core/src/main/java/btools/router/RoutingParamCollector.java
- brouter-core/src/test/java/btools/router/OsmNodeNamedTest.java
- brouter-mapaccess/src/main/java/btools/mapaccess/OsmFile.java
- brouter-mapaccess/src/main/java/btools/mapaccess/PhysicalFile.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java
- brouter-server/src/main/java/btools/server/RouteServer.java
- brouter-util/src/main/java/btools/util/CheapRuler.java
Here comes the new engineMode for roundtrips.
Parameters to play with:
direction - angle around start point (default random)
roundtripDistance - distance from start point (default 1500m)
roundtripDirectionAdd - changes the angle added to the direction (default 20 degrees)
allowSamewayback - go back the same way (default false)
exportWaypoints - export the generated points (default false)
profile:correctMisplacedViaPoints - correct the results (default false)
profile:correctMisplacedViaPointsDistance - distance for correction,  0 = don'r check distance (default 40m)
some samples:
direction = 90
direction 360 correctMisplacedViaPoints off
direction 360, correctMisplacedViaPoints on
direction 180 roundtripDirectionAdd 45deg
direction 360 allowSamewayback true
> New Roundtrip function

- brouter-server/src/main/java/btools/server/RouteServer.java
I stumbled upon on this issue while using Brouter for routing in my personal project.
Some background:
I have a web frontend that I'm locally serving from [Parcel's](https://parceljs.org/) dev server. To make requests to Brouter, I'm using a proxy feature of the dev server to forward certain requests to a locally running Brouter.
For a while, I was stumped by an error while trying to forward requests to Brouter:
```
[HPM] Error occurred while proxying request localhost:1234/brouter?lonlats=.......&format=geojson&profile=safety to http://localhost:17777/ [HPE_INVALID_HEADER_TOKEN] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
Turns out the proxy middleware it is utilizing does not like that headers are separated by just `LF`. By changing headers endings to `CRLF`, it …
> RFC7230 compliant HTTP header delimiter

- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
As discussed in #773, here comes the change.
It could be activated by `profile:continueStraight=1` or `assign continueStraight = true`.
The default is false.
For round trips this was the default setting, but now you can decide.
> Added a switch to avoid u-turns

- brouter-core/src/main/java/btools/router/FormatGpx.java
- brouter-core/src/main/java/btools/router/FormatJson.java
- brouter-core/src/main/java/btools/router/FormatKml.java
- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-core/src/main/java/btools/router/RoutingContext.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-core/src/main/java/btools/router/RoutingParamCollector.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java
- brouter-server/src/main/java/btools/server/request/ServerHandler.java
This is the PR for #769 
It brings a new parameter
```
exportCorrectedWaypoints=1
```
and added the reworked waypoints - if any - to the output formats gpx, kml and json.
The point have the new type `via_corr`
This allows clients to correct their via points and, in the event of a route change, only recalculate the sections before and after the moved point.
> Added export for corrected Via Points

- brouter-core/src/main/java/btools/router/FormatGpx.java
- brouter-core/src/main/java/btools/router/FormatJson.java
- brouter-core/src/main/java/btools/router/FormatKml.java
- brouter-core/src/main/java/btools/router/OsmTrack.java
- brouter-core/src/main/java/btools/router/RoutingEngine.java
- brouter-mapaccess/src/main/java/btools/mapaccess/MatchedWaypoint.java
- brouter-server/src/test/java/btools/server/RouteServerTest.java
Here a variant of the issue #519 
This should work with four situations on aroundabouts.
And the more complicated situation:
Please note that the correction of the via point is moved to the start of the roundabout. This should make it easier to move the second line later on.
> Mismatched point extention for roundabouts

- brouter-routing-app/build.gradle
- brouter-util/src/main/java/btools/util/StackSampler.java
We should also increase the `targetSdkVersion` to `35` or `36`.
As the updates on Google Play have such target requirement.
`StackSampler` demonstrates fixes for some deprecation warnings that appear when compiling with Android 16.
> Android 16

- brouter-routing-app/src/main/java/btools/routingapp/RoutingParameterDialog.java
The default selection of `ListPreference` in `RoutingParameterDialog` is not correct.
We should not compare with the array index, because the index is not always 0, 1, ...
For example in the hiking profile, the parameter [consider_traffic](https://github.com/abrensch/brouter/blob/master/misc/profiles2/hiking-mountain.brf#L18) index starts from `1`.
So now it selects as default the 2nd value instead of the correct 1st value.
It's better to compare with the real index (index=value) in the values of the array.
> Fix ListPreference in RoutingParameterDialog

- misc/profiles2/fastbike.brf
- misc/profiles2/hiking-mountain.brf
Because of the confusion from issue #810, the traffic handling has moved from `hiking-mountain` to the `fastbike` profile.
The hiking-mountain profile has no traffic handling now. Please let me know if needed.
> Profile: switched consider_traffic from hiking-mountain to fastbike

- brouter-routing-app/src/main/java/btools/routingapp/BRouterView.java
- brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java
In the discussion for #807 about profile and parameter we found that parameter changes made direct in BRouter are not used in routing.
I will examine `repeat:profile` function later on.
> Apk: Use profile parameter

- misc/profiles2/trekking.brf
Additionally to abandoned and proposed roads, it can be beneficial to avoid under construction roads.
For now, I only added this only to the `trekking` profile, as this is what i mostly use, but if desired, I can also add it to others. It already is somehow handled in the `hiking-mountain` and `mtb` profile.
Real world example: https://brouter.m11n.de/#map=14/48.1870/16.4440/standard&lonlats=16.419035,48.190981;16.46225,48.177006&profile=trekking
> Trekking: Exclude under construction roads
